### ISSUE TITLE
Every project created by Activator is copyright Typesafe

### ISSUE THREAD

**Issue by mslinn** [typesafehub/activator#1002]
This is the first line in a LICENSE file generated by Activator:

```
Copyright 2014 Typesafe, Inc.
```

That makes it appear that Typesafe claims ownership of all projects initiated by Activator as theirs. This is an optics problem, and is easily fixed. I suggest it be altered to something like this:

```
Copyright 2015 [Your company name or personal name here].
```

Here is how I generated the project with the LICENSE file:

```
 activator new x
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512M; support was removed in 8.0

Fetching the latest list of templates...

Browse the list of templates: http://typesafe.com/activator/templates
Choose from these featured templates or enter a template name:
  1) minimal-akka-java-seed
  2) minimal-akka-scala-seed
  3) minimal-java
  4) minimal-scala
  5) play-java
  6) play-scala
(hit tab to see a list of all templates)
> 4
OK, application "x" is being created using the "minimal-scala" template.

To run "x" from the command line, "cd x" then:
C:\work\experiments\scala\blah\x/activator run

To run the test for "x" from the command line, "cd x" then:
C:\work\experiments\scala\blah\x/activator test

To run the Activator UI for "x" from the command line, "cd x" then:
C:\work\experiments\scala\blah\x/activator ui

$ head -n +1 LICENSE
Copyright 2014 Typesafe, Inc.
```

**Comment by havocp** [comment]
Isn't the LICENSE copied from the template? In that case it's accurate, the initial code does have that copyright. It's like forking a project on GitHub; you don't become the copyright owner just because you made a copy.

If someone modifies the code to create a derived work then they would typically add their own copyright notice as well, leaving the owners as BOTH the original template author and the author of any modifications.

Fortunately the bsd-type license means the owner doesn't matter too much.

If we said "Copyright [your company]" that is legally inaccurate. Copyright can't be transferred like that; there would have to be a copyright assignment contract for the copyright owner to change.

For non-Typesafe templates there should be accurate copyright info reflecting the creator of those templates, of course.

Copyright owner and date is a factual question. The creator owns it until and unless they take steps to transfer ownership.

I would want to be careful not to add or modify copyright info that might be incorrect. At the time of template clone, the LICENSE on the template also applies to its new copy, right?

**Comment by mslinn** [comment]
Best to leave legal interpretations to lawyers. In the legal world, logic takes a back seat to precedent. Here is the first line of the [MIT license terms](http://en.wikipedia.org/wiki/MIT_License#License_terms):

    Copyright (c) <year> <copyright holders>

Here is the first line of the Apache v2 licence:

    Copyright [yyyy] [name of copyright owner]

If Typesafe wants to continue promoting the Apache v2 license (which I think is inferior to the MIT licence), then I suggest that the first line also follows Apache's example.

**Comment by havocp** [comment]
I am telling you what I believe a lawyer would say. When you clone a template, you now have some code in a directory. That code is copyrighted and has a copyright owner. We put the accurate copyright owner information on it as far as I know.  [name of owner] is supposed to be filled in with real info when applied to real code, and that's what we are doing.

What you're suggesting would provide people inaccurate information.

We are not giving you a sample or template license. We are giving you the actual license for the code.

The scenario is identical to cloning or forking a project on github. It would not be appropriate to fork a project and delete the copyright information.

**Comment by mslinn** [comment]
Here is a scenario:
 * User creates a project, without noticing the LICENSE file
 * User posts to github
 * Project violates someone else's copyright
 * That someone else's lawyer looks to see whom they can sue by reading the LICENSE file. Don't forget the [deepest pocket principal](http://en.wikipedia.org/wiki/Vicarious_liability_%28criminal%29)
 * Typesafe is served with a summons

Here is another scenario:
 * User creates a project, without noticing the LICENSE file
 * User posts to github
 * Use of the project by another user causes injury or death
 * etc.

Again, I suggest you folks get actual legal counsel on this. Developers are not qualified to make a judgement call in this matter, because logic is only a portion of what qualifies as sound legal advice.

Here is another scenario, this time from a PR point of view:
 * Someone wants to make themselves (in)famous as a "champion of the people"
 * They find out that Activator by default causes copyright to be assigned to Typesafe
 * A hyped article gets published in Wired, etc.
 * Bad Things Happen

There is no upside to claiming copyright for Typesafe by default, but there is a high degree of potential downside.

**Comment by havocp** [comment]
You are misunderstanding the situation. We are not "choosing" to claim copyright. The copyright owner is a legal fact about the existing template code.

We cannot provide a copyright for new code or changes that other people make. They have to do that.

Activator does NOT by default "assign copyright to Typesafe." It copies a template's LICENSE file along with the template's code, just as "git clone" clones the LICENSE. Legally this is identical to git clone.

I agree it's a problem that people put wrong copyrights on their stuff, but putting the wrong copyright on our stuff is not going to help, surely.

**Comment by mslinn** [comment]
*Please* escalate this so you folks get qualified legal advice on this. 

Once the Apache v2 license is applied to a project, [others may not change the license without express written permission, thus Typesafe will remain a copyright holder for all derivative works](https://www.apache.org/licenses/LICENSE-2.0#redistribution). 

The legal departments of clients and their investors will surely not permit any such encumbrance to their intellectual property. This is going to put a damper on using Activator, and the adoption of any technology that relies on Activator.

**Comment by mslinn** [comment]
I think the [Public Domain](http://en.wikipedia.org/wiki/Public_domain) is likely the best type of license for templates.

**Comment by havocp** [comment]
We have had an internal discussion / round of advice on this already. The resulting policy is documented under "licensing" on this page: https://typesafe.com/activator/template/contribute

we require a liberal license and suggest public domain (aka "CC0") for seed templates and Apache for tutorials.

Activator doesn't make this decision though. It's case by case and up to the template author. Activator just copies what the author puts in the file. 

I do think we intended to change some of Typesafe's seed templates to public domain and didn't do it yet. I'll confirm that. It isn't a change to Activator though, but to the templates. It will be up to other template authors how to copyright their stuff, except that we require something liberal (Apache style) to list in the catalog.

**Comment by mslinn** [comment]
All of this sounds exactly right :)

**Comment by lazaridis-com** [comment]
All templates (seed or not) **must** (by their nature) be `CC0` (not **should** but **must**).

Tutorials **should** be `CC0` (at least the code).

Typesafe should say: 
* Templates **must** be `CC0`, otherwise they are not accepted.
* "Tutorials have better chances to be accepted, if the are CC0 licensed"

**Comment by jsuereth** [comment]
Hey guys. These are all valid points about licensing.  Can you open issues on any template you find not abiding by these rules?

**Comment by mslinn** [comment]
I just ran a script that shows disappointing progress regarding seed projects (GNU licenses, invalid licenses, and mostly Apache licenses):

    for f in `activator list-templates|grep seed`; do activator new $f $f && less $f/LICENSE; done

**Comment by mslinn** [comment]
I just ran my script again. This issue has been ignored and has become worse.

56 seed projects now exist. No change for most seed projects: they still use the Apache or MIT license, except for the following which use the desirable CC0 license: cats-seed, finch-seed, libgdx-scala-seed, play-slick-codegen-flyway-seed, scala-forklift-with-slick-start-seed. **No Lightbend seed projects currently use CC0.**

Disturbingly, six seed projects fail to state a license. These should not be used: play-java-react-seed, primary-scala-scalatest-seed, primitive-scala-scalatest-seed, reactive-salesforce-rest-javascript-seed, salesforce-canvas-seed, spray-slick-seed.

**Comment by mikeyhew** [comment]
It is now October 2016. I just installed `activator`, and ran `activator new` choosing the "minimal-scala" template, and the license still says "Copyright 2014 Typesafe, Inc." with the Apache license.

It's been over a year, and employees of Typesafe (or rather, Lightbend after the name change) apparently hasn't changed anything, nor have any of their employees responded to this issue in that time. Needless to say, this does not look good for Lightbend. @jsuereth if you still work for Lightbend, please resolve this issue so people can use your tools!

I will now try to find the repository for the "minimal-scala" template, so I can post an issue there.

**Comment by eed3si9n** [comment]
Hi all, this is Eugene at Lightbend, and I'll take responsibility for sorting this out.
First of all, sorry about the inactions thus far. I haven't been aware of this issue, and I think I mostly agree with @mslinn's concerns.

**Comment by eed3si9n** [comment]
Now that sbt 0.13.13 is out with sbt `new`, we decided that the best way forward is just migrate actively used templates to Giter8 using CC0 and/or [Tech Hub](http://developer.lightbend.com/) examples.
