### ISSUE TITLE
Provide Mirrors for Asia/Australia

### ISSUE THREAD

**Issue by lazaridis-com** [typesafehub/activator#1011]
The team should not discuss latency in Asia/Australia (e.g. within #798), and instead do something to solve the latency problem, e.g. by providing mirrors. This is something one would expect from a company which produces development-tools for  distributed applications.

**Comment by jsuereth** [comment]
Activator is hosted on bintray.  Bintray is using Amazon's CloudFront.  Activator's templates are served via cloudfront.   AFAIK cloudfront SHOULD have mirrors.  We can talk with them about this.

**Comment by lazaridis-com** [comment]
@jsuereth , this issue remains **open** until **solved** (even your own comment confirms this).

**Comment by jsuereth** [comment]
If cloudfront doesn't have mirrors, the reality is we can't solve this, unless you're willing to set one up.   I'll do my best but this remains wontfix

**Comment by lazaridis-com** [comment]
* Verify if cloudfront has mirrors
* Verify if cloudfront has other solutions for the latency problem
* If not: get rid of cloudfront
* or: document clearly, that you wont fix the latency problem (which means of course that you declare Typesafe incapable).

until the above is done, this issue remain **open**

(this was my last try, keep it closed if you like, no problem at all for m)

**Comment by hepin1989** [comment]
cloudfront is blocked in China,so we always cross the wall :)cloudfront is blocked in China,so we always cross the wall :)
