### ISSUE TITLE
Issues building activator from source

### ISSUE THREAD

**Issue by damianball** [typesafehub/activator#1013]
Hello,

I'm trying to compile activator from source but I'm running into some issues. I've followed the instructions in the readme for the project, but it does not appear that my changes to (in this case, launcher) activator are showing up when I run what I've compiled. I realize that this is vague, but I'm not even sure where things are going wrong. Here are some things I've tried:

Clearing ~/.ivy2/local
Deleting and recloning the activator repo
Clearing ~/.ivy2/cache
rm -rf ~/.activator

`sbt stage` is successful, most of the time, and when it's finished I try to run `activator/dist/target/stage/activator new test play-java`

While this command will succeed, my changes to the output text are not showing up and it appears that neither are my code changes. It seems like my modifications to the source are either not captured, or somehow I'm not running the activator I compiled.

Any help would be greatly appreciated! Thank you.

**Comment by havocp** [comment]
There are various indirections involved with the launcher. To test just the UI, do `project activator-ui` and then `run` at the sbt prompt. But if you want to test the whole launcher or script, you have to jump through some hoops.

To test the launcher, you need to publishLocal; and then the launcher chooses a version first from the config created in `project/Packaging.scala` (which is probably the one you publishLocal'd) but overrides that with the version from http://www.typesafe.com/activator/latest unless you do -Dactivator.checkForUpdates=false every time you run the launcher to avoid creating `~/.activator/version-1.properties`. If you already have `version-1.properties` you can either delete it, or edit it to set the version you want the launcher to use.

Making it EVEN MORE FUN, once you publishLocal a given version, I think I've sometimes seen ivy fail to notice if you publish the same version again (it uses a stale cache).  

The key point though is that the launcher doesn't necessarily run the activator you have locally, it runs an activator that it resolves via ivy.

**Comment by damianball** [comment]
Thanks @havocp. Haha, yeah, looks like there is some complication with building. :-)

In this case, it was the stale cache that was causing me trouble. While I was clearing out the .ivy2 directories, I didn't realize .sbt was keeping a cache of the launcher.

/Users/<user>/.sbt/boot/scala-2.11.5/com.typesafe.activator/activator-launcher/

Do you think it would be useful to include some of these instructions in the activator repo? Something like a troubleshooting file.

Thanks again for the reply and help.

**Comment by havocp** [comment]
Absolutely would be useful to have some developer docs for Activator. Any chance you want to take a crack at a section in the README summarizing a few of the points here? It's fresh in your mind after all ;-)

**Comment by damianball** [comment]
I'd be happy to. I'll follow up here when I have a version to look at.

**Comment by jsuereth** [comment]
Going to mark this as resolved.  Thanks for hte README!
