### ISSUE TITLE
Failed to load sbt configuration

### ISSUE THREAD

**Issue by nguyener** [typesafehub/activator#1019]
I followed the "Akka and Cassandra" instruction (option 2) to download and run activator on my Ubuntu system.  When I ran ./activator ui, the browser came up with the menu.  However, after few minutes, I saw it showed a message said "Failed to load sbt configuration"

**Comment by henrikengstrom** [comment]
Hello @nguyener. Sorry to hear that it didn't work for you. Not sure exactly what you mean by option 2? What web site is it you're referring to? Also, what version of Ubuntu + Java are you using? Finally it'd be good if you could paste the output from Activator here so we can help you solve this issue.
Thanks,
Henrik

**Comment by nguyener** [comment]
Here is the akka web site:
http://www.typesafe.com/activator/template/activator-akka-cassandra 
JDK version: 1.8.0_40
Ubuntu version : 14.04.2

Btw, I found this from the terminal where I launch activator:
(process:28420): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed

**Comment by henrikengstrom** [comment]
That bug seems to be a Firefox related issue:
https://bugzilla.mozilla.org/show_bug.cgi?id=672671

Try using another browser and it should work.
Thanks for using Activator,
Henrik

**Comment by rkpantangi** [comment]
No, I see this error in Chrome also... disappointing..

**Comment by tenzan** [comment]
Yeah, it's happening in Chrome as well.

**Comment by tenzan** [comment]
It's interesting, it was reported 5 months ago, but this issue is kept closed. Why?
