### ISSUE TITLE
Cannot start new reactive-stocks example

### ISSUE THREAD

**Issue by alex88** [typesafehub/activator#1046]
Tried to create a new reactive stocks example, changed `sbt-echo` to `0.1.14` to fix #1038 and `sbt-fork-run-plugin` to `2.4.0` as per #1042 however during run I get:

```
Running (forked) play.core.server.DevServerStart 
objc[78771]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/bin/java and /Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.
Error: Main method not found in class play.core.server.DevServerStart, please define the main method as:
   public static void main(String[] args)
or a JavaFX application class must extend javafx.application.Application
```

**Comment by alex88** [comment]
Now with activator 1.3.5, created a play-scala seed, stuck on "Waiting for sbt server to restart"

**Comment by alex88** [comment]
Ok seems that in 1.3.5 it's working fine and the monitor mode is removed from the run panel, why has been removed?

**Comment by jsuereth** [comment]
The monitoring mode hasn't been updated for Play 2.4.0.  It's been removed pending some reworkings to the underlying APIs.

What I'd recommend in the meantime is to downgrade to activator 1.3.4 and stick with the version of play still supported (2.3.8).  You can do this by editing the file in ~/.activator/version-1.properties, and then starting activator using:  `activator -Dactivator.checkForUpdates=false ui`.

**Comment by alex88** [comment]
Awesome, thanks for explaining
