### ISSUE TITLE
Unable to create a project from templates

### ISSUE THREAD

**Issue by GajendraNaidu** [typesafehub/activator#1049]
With Activator-1.3.5-minimal, tried creating a project from template for 'play-reactive-mongo-polymer'.
I am getting error saying 'java.net.SocketException: Software caused connection abort: recv failed'

Tried many times, getting same error. There is no HTTP Proxy to internet. Below given is the info printed on console.

D:\typesafe\typesafe-activator-1.3.5-minimal\activator-1.3.5-minimal>activator ui
Checking for a newer version of Activator (current version 1.3.5)...
   ... failed to get latest version information: java.net.SocketTimeoutException: Read timed out
Found previous process id: 12224
Local repository: activator-launcher-local @ file:////D:/typesafe/typesafe-activator-1.3.5-minimal/activator-1.3.5-minimal/repository
Local repository: activator-local @ file:////D:/typesafe/typesafe-activator-1.3.5/activator-dist-1.3.5/repository
Play server process ID is 2544
[info] play - Application started (Prod)
[info] play - Listening for HTTP on /127.0.0.1:8888
[info] a.e.s.Slf4jLogger - Slf4jLogger started
[info] application - Failed to record a clone of 'play-reactivemongo-polymer': java.net.SocketException: Software caused connection abort: recv failed

**Comment by henrikengstrom** [comment]
Hello @GajendraNaidu 
Whenever this happens it is normally a hick-up with the internet connection somewhere (client or server side). Can you please try again and see if it works for you?
Thanks

**Comment by GajendraNaidu** [comment]
Thank you for the response.

Actually we had same problem with Play Framework application which I am developing.  All of a sudden without any code changes It stopped building application with the same issue. 

To isolate the problem, I tried creating a project with the new template and I am trying from last two days in various networks and various machines. In fact I tried in Linux and Windows as well. Same is response. Unable to understand what is going on.

**Comment by henrikengstrom** [comment]
During the startup of Activator we, amongst other things, check if the version you're running is the latest version. This is done by calling this URL: https://www.typesafe.com/activator/latest 
Can you check if you can access it directly in a browser please.

The exception you're seeing in the logs is logged from here:
https://github.com/typesafehub/activator/blob/master/launcher/src/main/scala/activator/ActivatorLauncher.scala#L178
It is therefore something inside the ``downloadLatestVersion`` method that causes the issue you experience.

**Comment by GajendraNaidu** [comment]
I could get this text from the URL you sent.

{"url":"http://downloads.typesafe.com/typesafe-activator/1.3.5/typesafe-activator-1.3.5.zip","miniUrl":"http://downloads.typesafe.com/typesafe-activator/1.3.5/typesafe-activator-1.3.5-minimal.zip","version":"1.3.5","size":"408M","miniSize":"1M","playVersion":"2.4.0","akkaVersion":"2.3.9","scalaVersion":"2.11.6","launcherGeneration":1}

I tried with activator-launch-1.2.12 as well same is the problem. Not getting any clue on what is happening.

**Comment by henrikengstrom** [comment]
Since you could get the information above in a browser my bet is that the connection to the server is quite slow and that it therefore times out. Right now there is a hard limit of 4s and if this is not fulfilled an exception will be thrown:
https://github.com/typesafehub/activator/blob/master/launcher/src/main/scala/activator/ActivatorLauncher.scala#L131

I will create a PR to increase the timeout period but this will not become available to you until there is a new release of Activator.

**Comment by GajendraNaidu** [comment]
Can I increase the hard limit? 
While we get the new release of Activator, is there any workaround to get things going?

**Comment by henrikengstrom** [comment]
Unfortunately there is, currently, no way around this hard limit unless you download the project, adjust the code and build a version locally. Let me know if you'd like to do this and I'll walk you through it.

**Comment by GajendraNaidu** [comment]
Thank you for your help and I will request you the help if we want to do that. 

I see an interesting issue which is part of this.
[error] Server access Error: Software caused connection abort: recv failed url=https://repo.typesafe.com/typesafe/ivy-releases/org.fusesource.leveldbjni/leveldbjni-win32/1.5/ivys/ivy.xml
[error] Server access Error: Software caused connection abort: recv failed url=https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.fusesource.leveldbjni/leveldbjni-win32/1.5/ivys/ivy

URLs does not exist if I browse. I get following response in browser 'The requested path was not found.'. Does this relate to the problem we are discussing.

**Comment by henrikengstrom** [comment]
It could be related. Do you mind pasting the full log output here so I can try to decipher what the issue could be.

**Comment by GajendraNaidu** [comment]
Here it is.
C:\RPTG-TFS\Aspect Portfolio\RPTG-OMNI\Dev\data_source_adapter\dsa_server>activator update 
[info] Loading project definition from C:\RPTG-TFS\Aspect Portfolio\RPTG-OMNI\Dev\data_source_adapter\dsa_server\project
Waiting for lock on C:\Users\gnaidu\.ivy2\.sbt.ivy.lock to be available...
[error] Server access Error: Software caused connection abort: recv failed url=https://repo.typesafe.com/typesafe/ivy-releases/org.fusesource.leveldbjni/leveldbjni-win32/1.5/ivys/ivy.xml
[error] Server access Error: Software caused connection abort: recv failed url=https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.fusesource.leveldbjni/leveldbjni-win32/1.5/ivys/ivy
.xml
[error] Server access Error: Software caused connection abort: recv failed url=https://repo.typesafe.com/typesafe/ivy-releases/org.fusesource.leveldbjni/leveldbjni-win64/1.5/ivys/ivy.xml
[error] Server access Error: Software caused connection abort: recv failed url=https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.fusesource.leveldbjni/leveldbjni-win64/1.5/ivys/ivy
.xml
[error] Server access Error: Software caused connection abort: recv failed url=https://repo.typesafe.com/typesafe/ivy-releases/io.apigee.trireme/trireme-core/0.7.5/ivys/ivy.xml
[error] Server access Error: Software caused connection abort: recv failed url=https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/io.apigee.trireme/trireme-core/0.7.5/ivys/ivy.xml
[error] Server access Error: Software caused connection abort: recv failed url=https://repo.typesafe.com/typesafe/ivy-releases/org.slf4j/slf4j-api/1.7.2/ivys/ivy.xml
[error] Server access Error: Software caused connection abort: recv failed url=https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.slf4j/slf4j-api/1.7.2/ivys/ivy.xml
[error] Server access Error: Software caused connection abort: recv failed url=https://repo.typesafe.com/typesafe/ivy-releases/io.apigee.trireme/trireme-node10src/0.7.5/ivys/ivy.xml
[error] Server access Error: Software caused connection abort: recv failed url=https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/io.apigee.trireme/trireme-node10src/0.7.5/ivys/ivy.xml

**Comment by henrikengstrom** [comment]
Thanks. I think this is an unrelated issue. (We have recently moved artifact over to Bintray). The timeout issue is something different. I will ask my colleagues in the Activator team to confirm my suspicion and thereafter create a PR to make the timeout period configurable.

**Comment by GajendraNaidu** [comment]
I have got it checked from our IT side to see why we were not downloading before timeout i.e 4 seconds. 
Interestingly they found the firewall is thinking these packages are harmful like false-positive scenario. This happens only when we use Activator to download libraries. If we use browser to download libraries, firewall is treating it as fine.

**Comment by corruptmemory** [comment]
Interesting.  Glad to hear you got to the bottom of this.  I'm going to close this issue.  If you need to follow-up please open a new issue.  Thanks for using Activator!
