### ISSUE TITLE
Bump to scala 2.11.7 please

### ISSUE THREAD

**Issue by netroby** [typesafehub/activator#1051]
The Scala 2.11.7 released, but activator still install scala 2.11.6 by default

```
Getting Scala 2.11.6 (for activator-launcher)...

```

**Comment by corruptmemory** [comment]
The version of Scala used in your project is under your control.  The version of Scala used by the Activator launcher and UI are independent of what you specify in your project:

Just put (or change if present) the following in your build:

```scala
scalaVersion := "2.11.7"
```

**Comment by corruptmemory** [comment]
As indicated by the above previous comment this should not be an issue using Activator.  Closing.
