### ISSUE TITLE
Activator won't start 1.3.5

### ISSUE THREAD

**Issue by xpavlic4** [typesafehub/activator#1055]
Version 1.3.5-minimal. Started activator.bat ui from the command line and following was opened in browser.

![image](https://cloud.githubusercontent.com/assets/771920/8493960/6adc843a-2160-11e5-9f35-294324eb2ec6.png)

**Comment by corruptmemory** [comment]
Did you see any errors or other output on the console?

**Comment by xpavlic4** [comment]
Absolutely nothing.

**Comment by corruptmemory** [comment]
Sorry for your troubles.

It looks like there is some strangeness in the local repositories.  As far as I can see you have a local repository for 1.3.5 and 1.3.2.  Also, it appears you're running Windows.  You can try following the instructions here: https://github.com/typesafehub/activator/issues/1054#issuecomment-118968809 to see if that helps.  Also, looking at the log files indicated in that comment may be useful in diagnosing what is going wrong.

**Comment by xpavlic4** [comment]
Deleted ~/activator and it works again! Thanks

**Comment by corruptmemory** [comment]
Awesome!  Thanks for using Activator.
