### ISSUE TITLE
Act. Distributed workers (Java) UnsupportedClassVersionError

### ISSUE THREAD

**Issue by thealy** [typesafehub/activator#1056]
Hi, Noob here. Working with fresh download of Activator on Ubuntu system running java version "1.8.0_45". All ok until the "Run the Application" step where workers are started in 3 terminal windows:

./activator "runMain worker.Main 3001"

These all die with: java.lang.UnsupportedClassVersionError: worker/Main : Unsupported major.minor version 52.0

Do I need to use an older Java version, or recompile something? 

Thanks.

**Comment by corruptmemory** [comment]
That typically means that you're trying to run Java 8 bytecode on an older version of Java.  What's the output of `java -version`?

**Comment by thealy** [comment]
"1.8.0_45"

**Comment by thealy** [comment]
Found that there was a mis-match in my .bashrc which defined JAVA_HOME to 1.7. Fixed that and they are running now.

Sorry to waste your time - thanks for reply.
