### ISSUE TITLE
Need help in evaluation scala code from browser

### ISSUE THREAD

**Issue by hardvain** [typesafehub/activator#1063]
I am creating a scala fiddle like app. I am looking to activator code to know how activator does it. Can anyone point me to the code where the JsValue is evaluated in the sbt server and how the results are sent back in the activator code base?

**Comment by corruptmemory** [comment]
Activator doesn't evaluate JavaScript on the server, merely uses JSON for the wire protocol.  Communication to the server is handled two ways:

1. AJAX calls: data is send as POST bodies to regular Play controllers
2. Websockets: via [WebSocketActor.scala](https://github.com/typesafehub/activator/blob/master/ui/app/activator/WebSocketActor.scala)

The Web socket actor is highly specialized and pre-dates a nice actor-based implementation currently found in Play: https://playframework.com/documentation/2.4.x/ScalaWebSockets#Handling-WebSockets-with-actors

Hope this helps.

**Comment by hardvain** [comment]
hi @corruptmemory 
As you said I am not trying to evaluate javascript from the browser. I am sending valid scala code as json response. I already dug into WebSocketActor.scala but I am having a hard time finding how the is evaluated by sbt. I want to know the handoff between the activator app and sbt server so that I can understand how to evaluate code in sbt programatically at runtime.

**Comment by corruptmemory** [comment]
Right, then you want to look at this: https://github.com/typesafehub/activator/blob/master/ui/app/activator/SbtClientActor.scala#L63

A JSON packet is parsed into a "command" and forwarded to the sbt server via the sbt client.

The details of sbt client/server can be found here: https://github.com/sbt/sbt-remote-control

**Comment by hardvain** [comment]
@corruptmemory  this was what I was looking for. Thanks a lot.

**Comment by jsuereth** [comment]
@hardvain would you say this is a closeable issue?

**Comment by corruptmemory** [comment]
Closing.  If more info is needed please open a new issue.
