### ISSUE TITLE
Place activator scripts in bin folder of zip distribution

### ISSUE THREAD

**Issue by marc0der** [typesafehub/activator#1091]
Currently the `activator`, `activator.bat` and `activator-launch-1.3.7.jar` artifacts are being deposited in the base directory of the zip distributions.

This is not common practice, as executable scripts are usually placed in the _bin_ directory, jars in the _lib_ directory.

In addition, a bin folder _is_ being created, but contains `activator-dist` and `activator-dist.bat` scripts (exact copies of their counterparts `activator` and `activator.bat` in the base folder), although these don't work because the jar file is not accessible from within the bin folder.

**Comment by marc0der** [comment]
@corruptmemory @henrikengstrom Hi guys, would it be possible for you to take a look at this PR please? We want to start distributing activator on [SDKMAN](http://sdkman.io) and this would make it possible.

**Comment by corruptmemory** [comment]
Honestly, looks good to me.  Happy to accept the PR.

**Comment by marc0der** [comment]
@corruptmemory @henrikengstrom Great, so do we need anything more to get it merged? Also, will there be a release sometime soon? We would like to make activator available on sdkman as soon as possible!

**Comment by marc0der** [comment]
@corruptmemory @henrikengstrom hi guys, any chance that this could be merged please?

**Comment by henrikengstrom** [comment]
@marc0der Sorry for not getting back to you. I will talk to @corruptmemory about merging this. Thanks.

**Comment by corruptmemory** [comment]
This has been merged and is part of Activator 1.3.8

**Comment by marc0der** [comment]
Thanks!
