### ISSUE TITLE
Activator Showing Unsupported version of Play 2.5.0

### ISSUE THREAD

**Issue by kishorenayar** [typesafehub/activator#1102]
I have downloaded latest Lightbend Activator from this [URL](https://playframework.com/download). But when I tried to run the project I'm getting the following error in the activator

**Using unsupported version of Play: 2.5.0**

**Comment by kishorenayar** [comment]
Changing in project/plugins.sbt with addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.4.6") is working for now. But I want to use 2.5.0, When I add that I'm always facing **Using unsupported version of Play: 2.5.0** in the activator UI which is not able to compile or run my project.

**Comment by benmccann** [comment]
Fix here: https://github.com/typesafehub/activator/pull/1103

**Comment by wannymiarelli** [comment]
Downloaded the last realease of the activator same issue.

**Comment by benmccann** [comment]
I don't think anyone's cut a new release with the fix yet.

@gmethvin @corruptmemory @eed3si9n think we'd be able to cut a release? We're getting lots of reports of this problem over on the Play side. Thanks!

**Comment by wannymiarelli** [comment]
Yes, i was just asking for a release ! Using activator new works fine, but i would like to use the UI command too. Thanks !

**Comment by aheinzer** [comment]
Yes, provide a new release please! I just wanted to try Play, followed the beginners tutorial and just ran into this problem. For learning Play, the UI would be very helpful.

**Comment by rstorey** [comment]
This bug causes my activator ui to go into an infinite loop trying to find a supported version of play.

**Comment by jkanniappan** [comment]
Still getting this issue and activator ui is compiling/building for ever...

**Comment by corruptmemory** [comment]
This should now be addressed in Activator 1.3.8
