### ISSUE TITLE
Unable to display <subproject>.routes file

### ISSUE THREAD

**Issue by sinel** [typesafehub/activator#265]
I have created a sub-project under modules by editing build.sbt, and then compiling in activator which automatically creates the necessary folders under modules/<subproject>. I can also create a build.sbt file under modules/<subproject> and edit it in activator. However, when I try to create a new routes file named <subproject>.routes under my new modules/<subproject> folder, I get an unable to display message and file content is not shown in activator. This happens whether I try to create the file from within activator, or I copy a routes file to this folder in Finder and rename.

How can I create and edit a routes file for my sub-project in activator?

**Comment by henrikengstrom** [comment]
Will close this issue due to missing feedback.
