### ISSUE TITLE
Project compilation fails with "scala.reflect.internal.MissingRequirementError: object scala.runtime in compiler mirror not found"

### ISSUE THREAD

**Issue by sandarenu** [typesafehub/activator#414]
I've just downloaded activator 1.0.13 and wanted to try it out. Activator UI was started successfully. But when I created a project and try to compile it following error appears.

<pre>
Refreshing list of source files to watch for changes...
Loading project definition from /home/sandarenu/activator-tests/hello-play/project
error: error while loading <root>, error in opening zip file
scala.reflect.internal.MissingRequirementError: object scala.runtime in compiler mirror not found.
Use 'last' for the full log.
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?
Failed to reload source file list: sbt process never got in touch, so unable to handle request WatchTransitiveSourcesRequest(true)
</pre>

I did a search on this and found this [Stackoverflow thread](http://stackoverflow.com/questions/18150961/scala-runtime-in-compiler-mirror-not-found-but-working-when-started-with-xboo). So I tried starting activator with `./activator -d -Dscala.usejavacp=true`. But still same issue comes. 

What could be the reason for this error?

**Comment by j-carvalho** [comment]
I'm also having this issue with activator-1.2.12. Have tried different solutions (removing .sbt, .ivy folder). Nothing seems to solve the problem. Any ideas?

**Comment by henrikengstrom** [comment]
Please try with the latest version of Activator. There should not be any issue installing/running it. If so, please create a new issue and we will take a look at it. 
Thanks for using Activator.
