### ISSUE TITLE
I can haz echo back?

### ISSUE THREAD

**Issue by jroper** [typesafehub/activator#421]
1. Run `activator new`.
2. When prompted for a project name, hit ctrl+c.
3. Terminal is left with echo off. (type `reset` and hit enter to fix)

**Comment by retronym** [comment]
+1 I'd suggest to copy the approach used in the Scala runner scripts, we capture the output of `stty` at the start of the script, and reset it on exit.

**Comment by retronym** [comment]
```

# Not sure what the right default is here: trying nonzero.
exit_status=127
saved_stty=""

# restore stty settings (echo in particular)
function restoreSttySettings() {
  stty $saved_stty
  saved_stty=""
}

function onExit() {
  [[ "$saved_stty" != "" ]] && restoreSttySettings
  exit $exit_status
}

# to reenable echo if we are interrupted before completing.
trap onExit INT

# save terminal settings
saved_stty=$(stty -g 2>/dev/null)
# clear on error so we don't later try to restore them
if [[ ! $? ]]; then  
  saved_stty=""
fi
```

The end of the script:
```
# record the exit status lest it be overwritten:
# then reenable echo and propagate the code.
scala_exit_status=$?
onExit
```

**Comment by retronym** [comment]
I tried to create a patch to do this, but I got stuck because of the way that `activator` uses `exec` to run Java. So my cleanup code wasn't triggered.

**Comment by retronym** [comment]
See also: https://github.com/sbt/sbt-launcher-package/blob/master/src/universal/bin/sbt-launch-lib.bash#L54-L56 https://github.com/paulp/sbt-extras/commit/f525931ca50e2196d04785db16a67738715c43c5
