### ISSUE TITLE
Default resolvers should use HTTPS

### ISSUE THREAD

**Issue by eleetas** [typesafehub/activator#628]
This should be done to prevent MITM attacks (one type of XBI attack) against the build process. Here's a recent discussion around this and maven: https://news.ycombinator.com/item?id=8099713

e.g. A work around for existing play projects is something like:
resolvers := Seq(
  "Typesafe Releases Repository" at "https://repo.typesafe.com/typesafe/releases/",
  "Typesafe Releases" at "https://repo.typesafe.com/typesafe/releases"
)

**Comment by benmccann** [comment]
I believe this is fixed. See https://github.com/typesafehub/activator/issues/763
