### ISSUE TITLE
Incorrect / Wrong test run count when running command activator test

### ISSUE THREAD

**Issue by rickarubio** [typesafehub/activator#662]
I currently have 2 test files in a Play! 2.3.2 project. I am running: 
* activator-launcher 1.2.8
* sbt launcher v0.13.5 
* activator 1.2.8

When I run
```
activator test
```

It seems like both test are run (I added println statements to each test), however, the test run count from activator seems to be wrong. Instead of reporting as 2 tests passed total, it only reports one.

```
info] Compiling 2 Java sources to /Users/bob1234/source/xyz/target/scala-2.11/test-classes...
Test 2 **************************************
test 1 =========================================
[info] Passed: Total 1, Failed 0, Errors 0, Passed 1
[success] Total time: 4 s, completed Aug 13, 2014 1:44:10 PM
```

**Comment by henrikengstrom** [comment]
Closing issue as it is fixed.
