### ISSUE TITLE
Tutorial is not part of downloaded zip archive

### ISSUE THREAD

**Issue by deanwampler** [typesafehub/activator#666]
I download spark-workshop (http://typesafe.com/activator/template/bundle/spark-workshop), unzip, open in the Activator UI running locally, no tutorial.

I've brought this up privately before, but forgot to open an issue.  For the spark-workshop, it's useless without the tutorial. As a temporary workaround, I've copied the entire markdown source for the tutorial to the root README.md, so at least the user has it.

**Comment by henrikengstrom** [comment]
Closing this issue as current setup, i.e. where tutorials reside, has been explained.
