### ISSUE TITLE
activator 1.2.10 forces sbteclipse-plugin to 2.3.0 (activator-sbt-eclipse-shim.sbt)

### ISSUE THREAD

**Issue by sebdotv** [typesafehub/activator#709]
Every time ```activator ui``` is executed, the file project/activator-sbt-eclipse-shim.sbt is generated with the following dependency: ```addSbtPlugin("com.typesafe.sbteclipse" % "sbteclipse-plugin" % "2.3.0")```

This prevents project customization of the sbteclipse-plugin version (more recent version 2.5.0 is required by some projects).

**Comment by henrikengstrom** [comment]
Closing this issue as it is no longer valid for latest version of Activator.
