### ISSUE TITLE
Play 2.3.4 unable to create new project [TimeOut Exception]

### ISSUE THREAD

**Issue by jroper** [typesafehub/activator#728]
Issue raised by @sxdemon at https://github.com/playframework/playframework/issues/3421:

I'm calling the activator to create a new project with the play-java template

activator new "projectName"
3
It always fail and I get the following error:

```
akka.pattern.AskTimeoutException: Ask timed out on [Actor[akka://default/user/template-cache#1973480390]] after [10000 ms]
at akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:333)
at akka.actor.Scheduler$$anon$7.run(Scheduler.scala:117)
at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:599)
at scala.concurrent.BatchingExecutor$class.execute(BatchingExecutor.scala:109)
at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:597)
at akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(Scheduler.scala:467)
at akka.actor.LightArrayRevolverScheduler$$anon$8.executeBucket$1(Scheduler.scala:419)
at akka.actor.LightArrayRevolverScheduler$$anon$8.nextTick(Scheduler.scala:423)
at akka.actor.LightArrayRevolverScheduler$$anon$8.run(Scheduler.scala:375)
at java.lang.Thread.run(Thread.java:745)
```

I tried to increase the timeout:

activator -Dactivator.timeout=30s
but I get the exception in less than a second regardless.

**Comment by SBSMMO** [comment]
I'll add my voice to this:

C:\Users\nshaw\dev\workspaces\test>activator new skalholt skalholt
Getting com.typesafe.activator activator-launcher 1.2.12 ...
downloading file:////C:/Users/nshaw/dev/activator-1.2.12/repository/com.typesafe.activator/activator-launcher/1.2.12/jars/activator-launcher.jar ...
        [SUCCESSFUL ] com.typesafe.activator#activator-launcher;1.2.12!activator-launcher.jar (24ms)
downloading file:////C:/Users/nshaw/dev/activator-1.2.12/repository/com.typesafe.activator/activator-props/1.2.12/jars/activator-props.jar ...
        [SUCCESSFUL ] com.typesafe.activator#activator-props;1.2.12!activator-props.jar (72ms)
downloading file:////C:/Users/nshaw/dev/activator-1.2.12/repository/com.typesafe.activator/activator-ui-common/1.2.12/jars/activator-ui-common.jar ...
        [SUCCESSFUL ] com.typesafe.activator#activator-ui-common;1.2.12!activator-ui-common.jar (125ms)
downloading file:////C:/Users/nshaw/dev/activator-1.2.12/repository/org.scala-sbt/completion_2.11/0.13.6/jars/completion_2.11.jar ...
        [SUCCESSFUL ] org.scala-sbt#completion_2.11;0.13.6!completion_2.11.jar (27ms)
downloading file:////C:/Users/nshaw/dev/activator-1.2.12/repository/org.scala-sbt/collections_2.11/0.13.6/jars/collections_2.11.jar ...
        [SUCCESSFUL ] org.scala-sbt#collections_2.11;0.13.6!collections_2.11.jar (26ms)
downloading file:////C:/Users/nshaw/dev/activator-1.2.12/repository/org.scala-sbt/control_2.11/0.13.6/jars/control_2.11.jar ...
        [SUCCESSFUL ] org.scala-sbt#control_2.11;0.13.6!control_2.11.jar (68ms)
downloading file:////C:/Users/nshaw/dev/activator-1.2.12/repository/org.scala-sbt/io_2.11/0.13.6/jars/io_2.11.jar ...
        [SUCCESSFUL ] org.scala-sbt#io_2.11;0.13.6!io_2.11.jar (19ms)
:: retrieving :: org.scala-sbt#boot-app
        confs: [default]
        30 artifacts copied, 0 already retrieved (19905kB/660ms)

Fetching the latest list of templates...

OK, application "skalholt" is being created using the "skalholt" template.

akka.pattern.AskTimeoutException: Ask timed out on [Actor[akka://default/user/template-cache#-583669740]] after [10000 ms]
        at akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:333)
        at akka.actor.Scheduler$$anon$7.run(Scheduler.scala:117)
        at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:599)
        at scala.concurrent.BatchingExecutor$class.execute(BatchingExecutor.scala:109)
        at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:597)
        at akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(Scheduler.scala:467)
        at akka.actor.LightArrayRevolverScheduler$$anon$8.executeBucket$1(Scheduler.scala:419)
        at akka.actor.LightArrayRevolverScheduler$$anon$8.nextTick(Scheduler.scala:423)
        at akka.actor.LightArrayRevolverScheduler$$anon$8.run(Scheduler.scala:375)
        at java.lang.Thread.run(Thread.java:722)

**Comment by tt7** [comment]
The title may be misleading since it is Activator that is raising the exception instead of Play. 
Actually NONE of the "featured templates" works in my case; even a simple minimal-java template will throw the same exception:

```
$ activator new test_java
Choose from these featured templates or enter a template name:
...
  3) minimal-java
...
> 3
OK, application "test_java" is being created using the "minimal-java" template.
// output omitted
To run the Activator UI for "test_java" from the command line, "cd test_java" then:
/data/sources/scala/test_java/activator ui

java.util.concurrent.TimeoutException: Futures timed out after [5 seconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
// output  omitted ......
```

**Comment by havocp** [comment]
There are several distinct timeout scenarios on this issue, I believe. I changed one that has in the past been 60s, 6s, and 12s (at different times) to 240s: https://github.com/typesafehub/activator/pull/981

The 60s => 6s change was a mistake, someone changed `60000` (milliseconds) to `6, SECONDS`. Then someone else thought the 6s was based on something and fixed it by only doubling it.

The 5s and 10s ones are somewhere else, not sure yet.

**Comment by havocp** [comment]
The 10s one was probably the one configurable via -Dactivator.timeout; I am changing the default to 25s from 10s

**Comment by havocp** [comment]
https://github.com/typesafehub/activator/pull/982

**Comment by tt7** [comment]
BTW, if the error message were more specific, maybe we could locate the error more effectively.

What is it waiting for? A HTTP request? What is the URI ?

**Comment by henrikengstrom** [comment]
Closing this issue as the timeout has been increased in #982 and this should improve the issue.

**Comment by Polariot** [comment]
Hey friend, 


I've  made some nice things, just look at them, you'll love them! Here  they are <http://modern.willanthonydesigns.com/lnguk>

Warmest, hansrueck

**Comment by Polariot** [comment]
Hey friend, 

There is something interesting I wanted  to tell you, I was really  surprised, just take a look <http://advantage.tjtherealtor.com/lnmax>

Sincerely, hansrueck

**Comment by Polariot** [comment]
Yo! 

Just take a look at that cool stuff  I  just  have found,  it's so fantastic! Here it is <http://spixungacre.powertalent.com/lnjuzls>

Looking forward, hansrueck

**Comment by Polariot** [comment]
Hey! 
Have you  seen this before? That's something really nice, more  info here <http://proquulano.elginnissan.com/lnqfn>

hansrueck

**Comment by Polariot** [comment]
Dear friend! 

I've just recieved  a message from my friend with great  news,  you'll  be surprised! Just read it here <http://josuwitu.spaatbalancewellspace.com/lnqfiw>

Yours, hansrueck
