### ISSUE TITLE
Security: Not all artifacts fetched over https

### ISSUE THREAD

**Issue by mveytsman** [typesafehub/activator#763]
Hi,

I am doing some follow-up work on my blogpost about insecure downloads of java artifacts (http://blog.ontoillogical.com/blog/2014/07/28/how-to-take-over-any-java-developer/).

I see that Activator merged a fix for this issue in August (https://github.com/typesafehub/activator/pull/674) . It appears to be insufficient.

I ran the following sequence of commands using a fresh install of activator 1.2.10 
```bash
activator new my-first-app play-scala
cd my-first-app
activator
```
and I found the following artifacts were downloaded over http

JARs and SHA hashes
http://repo1.maven.org/maven2/org/sonatype/sisu/sisu-guice/3.1.3/sisu-guice-3.1.3.jar 
http://repo1.maven.org/maven2/org/sonatype/sisu/sisu-guice/3.1.3/sisu-guice-3.1.3.sha1
http://repo.scala-sbt.com/scalasbt/sbt-plugin-releases/org.sonatype.sisu/sisu-guice/3.1.3/jars/sisu-guice.jar

Activator templates
http://downloads.typesafe.com/typesafe-activator/templates/9d/9d0dda/9d0dda78-90f2-4d7d-b596-d35a7246d20c.zip
http://downloads.typesafe.com/typesafe-activator/index/v2/index-0973541b048e73f9ee1acd04517a56c7fdde60f8.zip
                             
ivy.xml
http://repo.typesafe.com/typesafe/ivy-releases/sbt-run-support-210/sbt-run-support-210_2.10/0.1-SNAPSHOT/ivys/ivy.xml
http://repo.scala-sbt.com/scalasbt/sbt-plugin-releases/sbt-run-support-210/sbt-run-support-210_2.10/0.1-SNAPSHOT/ivys/ivy.xml
http://dl.bintray.com/sbt/sbt-plugin-releases/sbt-run-support-210/sbt-run-support-210_2.10/0.1-SNAPSHOT/ivys/ivy.xml

maven-metadata
http://repo1.maven.org/maven2/sbt-run-support-210/sbt-run-support-210_2.10/0.1-SNAPSHOT/maven-metadata.xml

pom files
http://repo1.maven.org/maven2/sbt-run-support-210/sbt-run-support-210_2.10/0.1-SNAPSHOT/sbt-run-support-210_2.10-0.1-SNAPSHOT.pom
http://repo.typesafe.com/typesafe/releases/sbt-run-support-210/sbt-run-support-210_2.10/0.1-SNAPSHOT/sbt-run-support-210_2.10-0.1-20141007.041953-1.pom

**Comment by benmccann** [comment]
PR for this here: https://github.com/typesafehub/activator/pull/827

**Comment by benmccann** [comment]
Btw, @mveytsman you might be interested in http://www.benmccann.com/blog/how-to-take-over-the-computer-of-a-jenkins-user/

**Comment by benmccann** [comment]
Hopefully this is fixed now since the PR was merged, so we can probably close this issue. Thanks @mveytsman for reporting and @jsuereth for finding the ones I missed in my earlier commit

**Comment by mveytsman** [comment]
Good to hear!

Thanks for the link @benmccann.

**Comment by benmccann** [comment]
We should close this issue now

**Comment by henrikengstrom** [comment]
Thanks @benmccann
