### ISSUE TITLE
checksums invalid sha1 where downloading jars

### ISSUE THREAD

**Issue by shijinkui** [typesafehub/activator#791]
:::: WARNINGS
problem while downloading module descriptor: http://xxx/activator-launcher/1.2.10/activator-launcher-1.2.10.pom
: invalid sha1: expected=554665c30cbe7187603e79930af547ef58d63b05 computed=fd03b057d1ab3ba85f5b63cea71c468eb9b162d8 (34ms)

problem while downloading module descriptor: http://xxx/repository/com/typesafe/activator/activator-launcher/1.2.10/activator-launcher-1.2.10.pom
: invalid sha1: expected=554665c30cbe7187603e79930af547ef58d63b05 computed=fd03b057d1ab3ba85f5b63cea71c468eb9b162d8 (25ms)

**Comment by henrikengstrom** [comment]
Sorry for very late response! Will close this issue as there is a new version of Activator available now.
