### ISSUE TITLE
Windows activator can't run in paths with exclamation marks

### ISSUE THREAD

**Issue by apYdr6uxv** [typesafehub/activator#814]
###### Description

`activator.bat` can't run in paths that have exclamation marks in them.
> :open_file_folder: `c:\coding\play!framework\project1\`

It will fail with:
>:boom: `Error: Unable to access jarfile`

###### Detective work

As far as I can tell, `ACTIVATOR_HOME` can't contain `!` because `!` is a special character to windows batch when doing `@SetLocal EnableDelayedExpansion`.

###### Attempts

I'm not qualified to fix this, but I tried (in vain) by:
- Setting `EnableDelayedExpansion` after the `ACTIVATOR_HOME`
- Modifying the string so that it prefixes `!` with `^`, which should escape it. 
     - But `^` need escaping too when writing them. No idea how to correctly do it, because by the time it hit the `java` calls, it still wasn't proper. For example, on the `java` line `ACTIVATOR_HOME` would be different than the one printed in an `echo` exactly afterwards (which incidentally had the correct format now); probably to do with how expanding works.

###### Temporary solutions

- Don't hold projects in a path with exclamations
- Run the JAR file manually

**Comment by henrikengstrom** [comment]
Hello @apYdr6uxv 
Thanks for reporting. 
I would try to refrain from using ``!`` in your path as this can cause all sorts of other issues. Just googling for it comes back with a lot results. 
Please let me know if this approach cause issues for you.

**Comment by henrikengstrom** [comment]
Closing this issue due to lack of feedback.
