### ISSUE TITLE
`activator run` paused at `[info] Loading project definition` for a long time

### ISSUE THREAD

**Issue by scotv** [typesafehub/activator#823]
I firstly created a project with:
```bash
activator new hello-reactivemongo play-reactive-mongo
```

then when I wanted to run this project, `activator` was **stopping at** `[info] Loading project definition from ...` **for a long time, no more errors or warnings.**

Is there any log files that I may check, and determine the reason of the pause?

```bash
$ cd hello-reactivemongo
$ activator run -v -d
```

```bash
# Executing command line:
java
-Dactivator.home=~/opt/activator-1.2.12
-Xms1024m
-Xmx1024m
-XX:PermSize=64m
-XX:MaxPermSize=256m
-jar
~/opt/activator-1.2.12/activator-launch-1.2.12.jar
run

[info] Loading project definition from ~/repo/hello-reactivemongo/project

```

*  I tried to open the verbose and debug option (`-v -d`), but no more other messages (as above);
*  I tried `activator run` other project of other template, like `play-scala`, it loaded and started 
`localhost:9000` quickly.

**Comment by henrikengstrom** [comment]
Hello @scotv 
Sorry for not getting back until now.

Could it have been some sort of network related issue when you tried to create the ``play-reactive-mongo`` template that cased it to stop? Do you still experience this issue?

**Comment by havocp** [comment]
this pause is downloading jars from the internet I believe. we want to add some feedback here but the easy things are silence or an enormous deluge of spam from Ivy, and it's hard to get something actually good.

**Comment by scotv** [comment]
Thanks @henrikengstrom 

I am not experience this issue and I agree with @havocp that it was a network issue of downloading jars. I forgot how I dealt with this issue, maybe I wait for a long time, or I changed my network environment.

However, I think the `[info]` should be more `verbose` like when we use `sbt`, it will list the steps:

```bash
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] downloading https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.10.4/scala-library-2.10.4.jar ...
[info]  [SUCCESSFUL ] org.scala-lang#scala-library;2.10.4!scala-library.jar (6413ms)
[info] downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.7/jars/sbt.jar ...
```
If `activator` stopped at `[info] downloading`, I may try to visit `https://...ivy-releases/...sbt.jar` in my Chrome, to determine that whether I can connect to that URL or not.

**Comment by henrikengstrom** [comment]
We should definitely try to improve the user feedback for this. I will create a ticket about this in our ticketing system so we don't forget about it.
Thanks for using Activator,
Henrik
