### ISSUE TITLE
With "fork := true" in your build, nothing appears in the log output in the run panel

### ISSUE THREAD

**Issue by deanwampler** [typesafehub/activator#841]
I need this setting to work around a Spark bug in my https://github.com/deanwampler/spark-workshop. However, absolutely no output appears in the log pane when you run a job with this setting. Comment it out, the output appears. The shell shows the output, although it mis-flags some runtime warnings as errors.

This effectively makes the activator UI unusable with this tutorial.

**Comment by henrikengstrom** [comment]
This seems to be resolved by the next version of Activator (1.3).
To be verified before closing the ticket.

**Comment by henrikengstrom** [comment]
This has been resolved in 1.3.0 of Activator so closing the ticket now.
