### ISSUE TITLE
reactive-maps templates requires typesafe subscription?

### ISSUE THREAD

**Issue by mustajarvi** [typesafehub/activator#845]
I'm using the 1.2.12 version and tried to create the reactive-maps template. When trying to compile the project i get an error:

	Loading details of this project...
	Loading project definition from /home/rikard/typesafe-activator/reactive-maps/project/project
	java.lang.RuntimeException: == Typesafe Reactive Platform: /home/rikard/typesafe-activator/reactive-maps/project/typesafe.properties was not found. project/typesafe.properties must exist with typesafe.subscription=<YOUR SUBSCRIPTION ID>.
	== Visit http://typesafe.com/account/id to obtain a trial subscription id.
	at scala.sys.package$.error(package.scala:27)
	at com.typesafe.rp.sbtplugin.TypesafeReactivePlatformIvyPlugin$$anonfun$globalSettings$7.apply(SbtPlugin.scala:164)
	at com.typesafe.rp.sbtplugin.TypesafeReactivePlatformIvyPlugin$$anonfun$globalSettings$7.apply(SbtPlugin.scala:158)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.EvaluateSettings$MixedNode.evaluate0(INode.scala:175)
	at sbt.EvaluateSettings$INode.evaluate(INode.scala:135)
	at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$submitEvaluate$1.apply$mcV$sp(INode.scala:69)
	at sbt.EvaluateSettings.sbt$EvaluateSettings$$run0(INode.scala:78)
	at sbt.EvaluateSettings$$anon$3.run(INode.scala:74)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
	== Typesafe Reactive Platform: /home/rikard/typesafe-activator/reactive-maps/project/typesafe.properties was not found. project/typesafe.properties must exist with typesafe.subscription=<YOUR SUBSCRIPTION ID>.
	== Visit http://typesafe.com/account/id to obtain a trial subscription id.
	Use 'last' for the full log.
	Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?
	Failed to load project details: sbt process never got in touch, so unable to handle request GenericRequest(true,name,Map())

Does this template require a typesafe subscription or is there something else which causes it?

I tried searching for issues but couldn't find anything I deemed related. 

I've tried other templates and they seem to work fine without a subscription.

**Comment by havocp** [comment]
Discussed also at https://github.com/typesafehub/ReactiveMaps/issues/25

If the template has a Reactive Platform dependency, there are two choices - get a free trial subscription (no time limit or obligation just not good for production deployment), or delete project/project/typesafe.sbt to port off of Reactive Platform.

**Comment by mustajarvi** [comment]
Ahh. Thanks for providing some light here.

The Reactive Platform is basically just a set of tested and verified versions of Scala/Play/Akka/Spray/Slick + some commercially supported DB drivers for Slick, right?

Can't see why this is needed here as long as the Activator template works.

The template compiles and runs now, but I get thousands of Actor Issues when I look at the Inspect page in the Activator ui and I don't see any map when I try to view the demo from a browser.

**Comment by henrikengstrom** [comment]
Sorry for the slow feedback @mustajarvi, 
Yes, Reactive Maps does generate a lot of actor issues so nothing wrong there. You should however see the map in your browser. Please try with the latest Activator version that can be downloaded here: http://typesafe.com/get-started

Hope that helps - if not feel free to open a new issue here.
Henrik
