### ISSUE TITLE
Play websocket actors are not shown at Inspector Tab

### ISSUE THREAD

**Issue by marceloemanoel** [typesafehub/activator#878]
Hi, guys.

I'm trying to inspect the actors created by play framework to handle websocket connections. The problem is that they're created under the `system` namespace and Inspector tab only shows actors from `user` namespace. I was wondering if it is possible to add an option to show `system`'s actors. It would help a lot.

Thanks in advance.

**Comment by henrikengstrom** [comment]
Hello @marceloemanoel 
Thanks for using Activator and Inspect. Unfortunately we have no plans to add ``system`` actors to Inspect. They are internal and therefore not of interest to most developers. 
Hopefully you can solve the problem you have at hand by other means.

**Comment by jroper** [comment]
@henrikengstrom This isn't actually true - Akka extensions can create system actors, and these may or may not be considered internal.  In this case, Play's websocket support (an Akka extension) manages actors supplied by users in its own hierarchy - this was recommended by @rkuhn, see

https://github.com/typesafehub/ReactiveMaps/pull/12

for the full discussion, specifically:

> please add a name for this actor; together with my above proposal it could be something like
>
>     /user/websockets/$bd/handler
>
> When moving this into Play proper the "websockets" actor should be moved into the "/system" namespace by using an Akka extension.

**Comment by pvlugter** [comment]
Activator doesn't trace system actors by default but they certainly can be traced. To trace all the play websocket actors, including the supervisor, use this sbt setting:

```scala
EchoKeys.traceable in Echo += "/system/websockets*" -> true
```

Or you can enable tracing for all system actors with:

```scala
EchoKeys.traceable in Echo += "/system/*" -> true
```

They should then show up in Activator Inspect.

**Comment by henrikengstrom** [comment]
Thanks for reminding me about this setting @pvlugter.

@marceloemanoel apart from the settings above you must also make sure to import the ``EchoKeys`` into your sbt file (build.sbt) with ``import com.typesafe.sbt.SbtEcho._`` and you should be good to go.
