### ISSUE TITLE
Activator run app in foreground (Docker support)

### ISSUE THREAD

**Issue by lukaswelte** [typesafehub/activator#939]
To run activator in a Development Environment inside docker it would be necessary to run activator run as command inside a docker container. 
Right now Docker would terminate when the application starts. 

Would be awesome to see support for this, as live reloading during development is a absolute want feature.

**Comment by havocp** [comment]
I'm not sure I understand correctly - "run" should normally block. Maybe this is a Play application, and when it says "ctrl+D to stop" docker is putting /dev/null on standard input and that shuts down Play immediately? What output do you see when you do "activator run"?

**Comment by lukaswelte** [comment]
Correct, this is a Play application. 
It compiles and as soon as the application start is printed the Container terminates.

The output above is when starting Docker in fig (exact same output except the `web_1` when I would start it directly via Docker).  The CMD ist activator run

```bash
[info] Resolving jline#jline;2.12 ...
web_1 | [info] Done updating.
web_1 | 
web_1 | --- (Running the application, auto-reloading is enabled) ---
web_1 | 
web_1 | [info] play - Listening for HTTP on /0:0:0:0:0:0:0:0:9000
web_1 | 
web_1 | (Server started, use Ctrl+D to stop and go back to the console...)
web_1 | 
web_1 | 
web_1 | [success] Total time: 34 s, completed Feb 19, 2015 7:54:53 AM
web_1 exited with code 0
Gracefully stopping... (press Ctrl+C again to force)
```

**Comment by freiguy1** [comment]
I just tried supporting my app with docker yesterday and also ran into the same issue.  It seems like the comment [here](https://registry.hub.docker.com/u/ingensi/play-framework/) was experiencing the same thing.

**Comment by havocp** [comment]
I think you all know this but I want to be sure bystanders and googlers know that we're talking about dev mode here. In prod there's no issue (see https://www.playframework.com/documentation/2.3.x/Production  ).

The fix for dev mode would really be in play rather than activator I think. They would need a version of the run command that doesn't care about EOF on standard
input. Activator is simply invoking the play plugin here. So it might be good to relocate this issue to the play issue tracker.

**Comment by lukaswelte** [comment]
I opened this issue to the play framework repository.

**Comment by henrikengstrom** [comment]
Closing this ticket as it seems to be a Play related issue.
