### ISSUE TITLE
Run menu doesn't scroll

### ISSUE THREAD

**Issue by deanwampler** [typesafehub/activator#954]
The run menu doesn't scroll when the list is too long to fit the screen. (Bringing up the Mac OS Dock when the mouse scrolls to the bottom of the screen is a bonus...)

V1.3.0-M10

![run menu issue](https://cloud.githubusercontent.com/assets/3991/6336919/c313ca06-bb6b-11e4-8e59-9f74c54ef2d5.jpg)

**Comment by Warry** [comment]
Fixed on master
