### ISSUE TITLE
Make the http port configuration project dependent

### ISSUE THREAD

**Issue by pinus14** [typesafehub/activator#955]
The usecase are multiple play applications running on the same machine. I want to be able to checkout the source and run the application with a generic command. This currently does not because all want to run on port 9000.
It would be useful if the activator would read e.g. .activator file and set the X_OPTS according to this file. This would enable to check in the file in the repository and everybody who checks out the app runs it on a pre-defined port. If you have multiple services working together this really would ease the startup.

**Comment by henrikengstrom** [comment]
Hello @pinus14 
You can already now define things like Play port etc by creating a file called ``activatorconfig.txt`` and put in your either of ``~/.activator/`` or ``~/.activator/<activator version>/`` folders.
Hope this is good enough for your needs.
Thanks for using Activator,
Henrik

**Comment by pinus14** [comment]
No this is again a configuration per user, not per per project. What I need is a configuration per project. For me it doesn't make any difference if you configure in environment variables or configuration file. It is bound to a user.
What I need are different configurations with one user, per project. What I need is a $projectDir/.activator configuration.

**Comment by havocp** [comment]
are you talking about the port activator ui runs on or that the play app runs on?

For the play app, that's independent of activator - you would configure it in your build. I think it might be `javaOptions in run += "-Dhttp.port=9001"`  but I'm not at my computer to test.

**Comment by pinus14** [comment]
For me this doesn't work. I created a fresh Play project, added 
javaOptions in run += "-Dhttp.port=9001"
to the the end of the build.sbt and called "activator run". The app is available on port 9000, NOT on 9001. Using activator 1.3.2.

**Comment by havocp** [comment]
For javaOptions to work you need to be using the new forking run stuff (fork in run := true, then run with backgroundRun), though that may not be the whole issue. Plain "run" is the old Play run which doesn't fork, so javaOptions can't do anything.

If this doesn't work, the right fix is probably that we should make it work.

**Comment by pinus14** [comment]
If you think this should work, not for me.

name := """Demo"""

version := "1.0-SNAPSHOT"

lazy val root = (project in file(".")).enablePlugins(PlayScala)

scalaVersion := "2.11.5"

libraryDependencies ++= Seq(
  jdbc,
  anorm,
  cache,
  ws
)

fork in run := true

javaOptions in run += "-Dhttp.port=9001"


...
[info] Done updating.

--- (Running the application, auto-reloading is enabled) ---

[info] play - Listening for HTTP on /0:0:0:0:0:0:0:0:9000

**Comment by havocp** [comment]
this is with backgroundRun? can you open an issue on playframework about it? The fix here would be in the play sbt plugin.

**Comment by henrikengstrom** [comment]
@pinus14 how do you run the Play app?
If I use your setting in the Activator UI the Play app starts on the port specified (i.e. 9001).

**Comment by pinus14** [comment]
pinus@xxxxx-pc:~/Development/Scala/Demo$ ls
activator                   app        conf     logs     public  target
activator-launch-1.3.2.jar  build.sbt  LICENSE  project  README  test
haug@haug-pc:~/Development/Scala/Demo$ ./activator run
[info] Loading project definition from /home/haug/.data/development/Scala/Demo/project
[info] Set current project to Demo (in build file:/home/haug/.data/development/Scala/Demo/)

--- (Running the application, auto-reloading is enabled) ---

[info] play - Listening for HTTP on /0:0:0:0:0:0:0:0:9000

(Server started, use Ctrl+D to stop and go back to the console...)

**Comment by havocp** [comment]
so it sounds like this is a play bug that it only forks with backgroundRun and not plain run. I'm not sure they will want to change that in a stable release but it should be fixed in a future major release. it isn't an activator issue as far as I know.

**Comment by henrikengstrom** [comment]
Closing this issue as the issue seems to be related to Play not Activator.
