### ISSUE TITLE
Pop down run menu won't display long fully-qualified names

### ISSUE THREAD

**Issue by deanwampler** [typesafehub/activator#969]
Activator v1.3.0:

![image](https://cloud.githubusercontent.com/assets/3991/6413940/9bb11a86-be59-11e4-9681-9f5561e39df9.png)

Note how most of the names are cut off. I can certainly use shorter package names. I did that with my original spark-workshop template to work around a similar problem. However, this will certainly byte many people. Either menu should be wide enough to show the fully-qualified names (preferred) or it should truncate from the front, not the back.

**Note:** The project shown is also named `spark-workshop` (my bad), but it's actually a different project for training purposes.

**Comment by Warry** [comment]
https://github.com/typesafehub/activator/pull/970 <- fixed

**Comment by Warry** [comment]
It's merged, therefore it'll be in 1.3.1. Thanks for reporting Dean :)
