### ISSUE TITLE
Please add quickly installation shell scripts

### ISSUE THREAD

**Issue by netroby** [typesafehub/activator#984]
For example, we can create a curl scripts
User want to install activator, can execute the following scripts

```
curl https://www.typesafe.com/download/activator/install.sh | sh
```

curl download the activator and launcher, put them into user home directory /bin 

```
cd $HOME/bin
curl -C - -L -O https://www.typesafe.com/download/activator/minimal.tgz 
tar zxvf minimal.tgz
unlink minimal.tgz
```

**Comment by henrikengstrom** [comment]
Thanks for your suggestion @netroby 
Although this is a nice feature we currently have no time to implement it. Will revisit if there is some time left over in the near future.
Thanks for using Activator.

**Comment by netroby** [comment]
@henrikengstrom do you need help ? i would like to help you implement this.I have some free time to contribute.
