### ISSUE TITLE
Activator doesn't pass jvm parameters for sbt  

### ISSUE THREAD

**Issue by fdobrotv** [typesafehub/activator#989]
We have Play-java application, which we test by starting shell command:
/opt/activator/activator-1.3.2/activator -Dsbt.log.noformat=true -Duser.timezone=GMT+3 "test-only  -- -Dactivemap.domain=*.geo4.me -Dactivemap.login=****** -Dactivemap.password=****** -Dactivemap.cerebellum.port=9099 -Duser.timezone=GMT+3" -d

After start it has print 
Executing command line:
java
-Dactivator.home=/opt/activator/activator-1.3.2
-Xms1024m
-Xmx1024m
-XX:MetaspaceSize=64m
-XX:MaxMetaspaceSize=256m
-Duser.timezone=GMT+3
-Dsbt.log.noformat=true
-Duser.timezone=GMT+3
-jar
/opt/activator/activator-1.3.2/activator-launch-1.3.2.jar
"test-only  -- -Dactivemap.domain=*.geo4.me -Dactivemap.login=****** -Dactivemap.password=****** -Dactivemap.cerebellum.port=9099 -Duser.timezone=GMT+3"

and have in test's code:
        System.out.println("test runned with " + System.getProperty("user.timezone"));
        System.out.println("timezone in test is " + TimeZone.getDefault().getDisplayName());

Which print us:
test runned with GMT+3
timezone in test is Greenwich Mean Time

But if we set -Duser.timezone=GMT+3 parameter in build.sbt as:
javaOptions in Test ++= Seq(
 "-Dfile.encoding=UTF-8"
 "-Duser.timezone=GMT+3"
)

we get next results:
test runned with GMT+3
timezone in test is GMT+03:00

and tests pass successfully.

Normal application start, without tests, doesn't need such approach.

How we can send this parameters correctly through activator sh/cmd ?
Maybe this is a bug?

Activator 1.3.2.
cat /var/lib/jenkins/.activator/1.3.2/activatorconfig.txt
-Duser.timezone=GMT+3

**Comment by jsuereth** [comment]
This appears to be more of an sbt issue.  Do you see the same issue using an sbt script?


Related, are you forking your tests? That's the only way sbt's "javaOptions" settings will work, and by default I'm not sure if sbt will forward property variables to forked JVMs.   i.e. I think things are working as intended.
