### ISSUE TITLE
Error during running "activator ui": unresolved akka dependency.

### ISSUE THREAD

**Issue by codingcrystal** [typesafehub/activator#990]
While trying to run typesafe activator I got following error:
E:\activator-1.3.2-minimal>activator ui
Getting com.typesafe.activator activator-ui 1.3.2 ...
...
com.typesafe.akka#akka-slf4j_2.11;2.3.9: configuration not found in com.typesafe.akka#akka-slf4j_2.11;2.3.9: 'compile'. It was required from com.typesafe.trace#echo-collect211;0.1.12 compile
...
unresolved dependency: com.typesafe.akka#akka-slf4j_2.11;2.3.9: configuration not found in com.typesafe.akka#akka-slf4j_2.11;2.3.9: 'compile'. It was required from com.typesafe.trace#echo-collect211;0.1.12 compile
Error during sbt execution: Error retrieving required libraries (see ...\update.log for complete log)
Error: Could not retrieve activator-ui 1.3.2

**Comment by havocp** [comment]
This is most likely either a transient network problem or a corrupted ivy cache (~/.ivy2/cache).

**Comment by havocp** [comment]
(If you make a test user account and try in a clean home directory, there's a good chance it won't break in the same way. You could also try moving ~/.ivy2/cache aside temporarily, but it's quite a large directory for most people so a lot to re-download.)

**Comment by codingcrystal** [comment]
Thanks, @havocp!
Cleaning ivy cache fixed the problem for me.
