### ISSUE TITLE
modern-web-template: problems to run with activator ui

### ISSUE THREAD

**Issue by sergius** [typesafehub/activator#991]
__UPDATE__
Please discard the previous issue, it was solved after a clean restart of MongoDB and I can run the application without problems with `sbt run`

Nevertheless, it doesn't work well when trying to run from `actviator ui`. That's all it shows:

![play-error](https://cloud.githubusercontent.com/assets/328832/6909815/7136f956-d74a-11e4-96bc-d14384416dd8.png)

----

Tried to run it in two ways:
 * `../modern-web-template >  sbt run`
 * ````
   ../modern-web-template > activator
    [modern-web-template] > start
  ```

Opening the page causes no problems. 
As soon as you try to add a new user it crashes  with reactivemongo error.

**Comment by havocp** [comment]
Thanks for the report! This looks like an issue with the specific template, so should be reported to the template author probably.

**Comment by sergius** [comment]
You're right, I will. Though, as it works well outside `activator`, I thought it might be having an issue, too.

**Comment by havocp** [comment]
You may be right - I'm hoping the template author would be able to narrow down the `activator ui` issue a bit and let us know what we need to fix.

**Comment by jsuereth** [comment]
Closing this in favor of the ticket on the underlying template.  Please reopen any specific activator ui issues :)
