### ISSUE TITLE
void

### ISSUE THREAD

**Issue by lazaridis-com** [typesafehub/activator#995]

**Comment by havocp** [comment]
The direction we've been taking is that sbt itself is the "unbranded" version, and we want to factor more of the activator codebase out so it's present in sbt. At that point activator will be a "spin" of sbt that adds the branded elements. (It already is, more or less, but we can make it more so.)

**Comment by lazaridis-com** [comment]
This sounds good. The direction you've taken seems to be the right one. And if you provide enough 'brandability', then the look&feel (and the benefits, like e.g. simplified documentation & handling) of a fully 'branded' Play! could be easily demonstrated.

**Comment by lazaridis-com** [comment]
would solve #92
